build:
  date: '@build.date@'

logging:
#  file:
#    name: ./checklist.log
  level:
    org:
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
      sringframework:
        boot: DEBUG
        security: DEBUG
    root: INFO

server:
  #address: localhost
  compression:
    enabled: true
  mime-types: application/json,application/xml,text/xml,text/plain,application/javascript,text/css,text/html,text/event-stream
  port: 8082
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore/ssafy.p12
#    key-store-password: doglivedoggi
#    key-alias: ssafy
#    trust-store: classpath:keystore/ssafy.ts
#    trust-store-password: doglivedoggi
  servlet:
    contextPath: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
http-server:
  http:
    port: 8082

spa:
  default-file: /dist/index.html

spring:
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql : true
        format_sql : true
        use_sql_comment: true

  mvc:
    throw-exception-if-no-handler-found: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

  web:
    resources:
#      add-mappings: false
      static-locations: classpath:/dist/

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://j5checklist.p.ssafy.io:3306/checklist?serverTimezone=Asia/Seoul
      username: root
      password: ssafy406!@!@


